//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Services_Rest.Dmain.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class productosDbEntities : DbContext
    {
        public productosDbEntities()
            : base("name=productosDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<perfilUsuario> perfilUsuario { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
        public virtual DbSet<UsuarioRoles> UsuarioRoles { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
