//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Services_Rest.Dmain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int idDireccion { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public string NumInterior { get; set; }
        public string NumExterior { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> idPerfilUsuario { get; set; }
    
        public virtual perfilUsuario perfilUsuario { get; set; }
    }
}
