//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Services_Rest.Dmain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int idTelefono { get; set; }
        public string celular { get; set; }
        public string casa { get; set; }
        public string oficina { get; set; }
        public Nullable<int> idPerfilUsuario { get; set; }
    
        public virtual perfilUsuario perfilUsuario { get; set; }
    }
}
