//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Services_Rest.Dmain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioRoles
    {
        public int idUsuarioRoles { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idRoles { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
